# 01_Initial Data Exploration

This notebook performs the initial exploration of the raw Olist e-commerce datasets to understand their structure, quality, and key characteristics prior to transformation.

The analysis includes:

- **Loading and inspecting raw datasets**  

- **Dataset structure analysis**, reviewing row counts, column definitions, and data types  

- **Missing data and duplicate detection**, identifying potential data quality issues  

- **Value distribution analysis**, examining ranges and unique values for key variables  

- **Preliminary data quality assessment**, identifying anomalies and inconsistencies that may impact downstream processing  

The goal of this step is to establish a clear understanding of the raw data and highlight data quality considerations before proceeding to data preparation, validation, and warehouse loading.

## 1.Load the Datasets

In [ ]:
import os
import pandas as pd

In [ ]:
#cd documents/olist_ecommerce/data/raw
os.getcwd()

In [198]:
df_customers=pd.read_csv('../data/raw/olist_customers_dataset.csv')
df_geolocation=pd.read_csv('../data/raw/olist_geolocation_dataset.csv')
df_order_item=pd.read_csv('../data/raw/olist_order_items_dataset.csv')
df_order_payments=pd.read_csv('../data/raw/olist_order_payments_dataset.csv')
df_order_review=pd.read_csv('../data/raw/olist_order_reviews_dataset.csv')
df_orders=pd.read_csv('../data/raw/olist_orders_dataset.csv')
df_products=pd.read_csv('../data/raw/olist_products_dataset.csv')
df_sellers=pd.read_csv('../data/raw/olist_sellers_dataset.csv')
df_product_category=pd.read_csv('../data/raw/product_category_name_translation.csv')

## 2.Load and Initial Profiling of 'Customer Datset'

In [ ]:
#check the shape of the customer datset
print(f'Customer Dataset Shape:',df_customers.shape)
df_customers.head()

Customer Dataset Shape: (99441, 5)


,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,franca,SP
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,9790,sao bernardo do campo,SP
2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,1151,sao paulo,SP
3,b2b6027bc5c5109e529d4dc6358b12c3,259dac757896d24d7702b9acbbff3f3c,8775,mogi das cruzes,SP
4,4f2d8ab171c80ec8364f7c12e35b23ad,345ecd01c38d18a9036ed96c73b8d066,13056,campinas,SP


In [200]:
#check for missing values
df_customers.isna().sum()

customer_id                 0
customer_unique_id          0
customer_zip_code_prefix    0
customer_city               0
customer_state              0
dtype: int64

In [201]:
#inspect the dataset structure and data types
df_customers.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 5 columns):
 #   Column                    Non-Null Count  Dtype 
---  ------                    --------------  ----- 
 0   customer_id               99441 non-null  object
 1   customer_unique_id        99441 non-null  object
 2   customer_zip_code_prefix  99441 non-null  int64 
 3   customer_city             99441 non-null  object
 4   customer_state            99441 non-null  object
dtypes: int64(1), object(4)
memory usage: 3.8+ MB


In [202]:
#check for duplicated rows
df_customers.duplicated().sum()

np.int64(0)

In [203]:
#check the number of unique customer_id records
df_customers['customer_id'].nunique()

99441

In [204]:
#check the number of unique real customers in the dataset
df_customers['customer_unique_id'].nunique()

96096

**Notes:**

One real customer (customer_unique_id) can have multiple customer records (customer_id).

The number of unique customer identifiers exceeds the number of unique real customers, indicating repeat customer records per individual.

In [205]:
#check if the count of the customer_id is same as the shape of the datset
df_customers['customer_id'].value_counts().sum()==df_customers.shape[0]

np.True_

In [206]:
#count the number of customers per city
df_customers['customer_city'].value_counts()

customer_city
sao paulo            15540
rio de janeiro        6882
belo horizonte        2773
brasilia              2131
curitiba              1521
                     ...  
bequimao                 1
andarai                  1
vargem grande            1
curvelandia              1
eugenio de castro        1
Name: count, Length: 4119, dtype: int64

In [207]:
#count the number of customers per zip code
df_customers['customer_zip_code_prefix'].value_counts()

customer_zip_code_prefix
22790    142
24220    124
22793    121
24230    117
22775    110
        ... 
35698      1
99370      1
64808      1
60876      1
99043      1
Name: count, Length: 14994, dtype: int64

In [208]:
#count the number of unique customer cities
df_customers['customer_zip_code_prefix'].nunique()

14994

In [209]:
#check the min values of each column to identify potential out of range values
df_customers.min()

customer_id                 00012a2ce6f8dcda20d059ce98491703
customer_unique_id          0000366f3b9a7992bf8c76cfdf3221e2
customer_zip_code_prefix                                1003
customer_city                            abadia dos dourados
customer_state                                            AC
dtype: object

In [210]:
#check the max values of each column to identify the potential out of range values
df_customers.max()

customer_id                 ffffe8b65bbe3087b653a978c870db99
customer_unique_id          ffffd2657e2aad2907e67c3e9daecbeb
customer_zip_code_prefix                               99990
customer_city                                         zortea
customer_state                                            TO
dtype: object

In [ ]:
#check the count of customers in each state
df_customers['customer_state'].value_counts()

customer_state
SP    41746
RJ    12852
MG    11635
RS     5466
PR     5045
SC     3637
BA     3380
DF     2140
ES     2033
GO     2020
PE     1652
CE     1336
PA      975
MT      907
MA      747
MS      715
PB      536
PI      495
RN      485
AL      413
SE      350
TO      280
RO      253
AM      148
AC       81
AP       68
RR       46
Name: count, dtype: int64

In [ ]:
#check the count of customers in each city
df_customers['customer_city'].value_counts()

customer_city
sao paulo            15540
rio de janeiro        6882
belo horizonte        2773
brasilia              2131
curitiba              1521
                     ...  
bequimao                 1
andarai                  1
vargem grande            1
curvelandia              1
eugenio de castro        1
Name: count, Length: 4119, dtype: int64

In [213]:
#count the number of unique customer cities
df_customers['customer_city'].nunique()

4119

In [ ]:
#count the number of unique customer states
df_customers['customer_state'].nunique()

27

## 3.Load and Initial Profiling of 'Geolocation Datset'

In [ ]:
#check the shape of the geolocation datset
print(f'Geolocation Dataset Shape:',df_geolocation.shape)
df_geolocation.head()

Geolocation Dataset Shape: (1000163, 5)


,geolocation_zip_code_prefix,geolocation_lat,geolocation_lng,geolocation_city,geolocation_state
0,1037,-23.545621,-46.639292,sao paulo,SP
1,1046,-23.546081,-46.644820,sao paulo,SP
2,1046,-23.546129,-46.642951,sao paulo,SP
3,1041,-23.544392,-46.639499,sao paulo,SP
4,1035,-23.541578,-46.641607,sao paulo,SP


In [ ]:
#inspect the dataset structure and data types
df_geolocation.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000163 entries, 0 to 1000162
Data columns (total 5 columns):
 #   Column                       Non-Null Count    Dtype  
---  ------                       --------------    -----  
 0   geolocation_zip_code_prefix  1000163 non-null  int64  
 1   geolocation_lat              1000163 non-null  float64
 2   geolocation_lng              1000163 non-null  float64
 3   geolocation_city             1000163 non-null  object 
 4   geolocation_state            1000163 non-null  object 
dtypes: float64(2), int64(1), object(2)
memory usage: 38.2+ MB


In [ ]:
#check for missing values
df_geolocation.isna().sum()

geolocation_zip_code_prefix    0
geolocation_lat                0
geolocation_lng                0
geolocation_city               0
geolocation_state              0
dtype: int64

In [ ]:
#check for duplicated rows
df_geolocation.duplicated().sum()

np.int64(261831)

In [ ]:
#check the number of unique zip code in the dataset
df_geolocation['geolocation_zip_code_prefix'].nunique()

19015

In [ ]:
#check the minimum number of each column in the dataset
df_geolocation.min()

geolocation_zip_code_prefix          1001
geolocation_lat                -36.605374
geolocation_lng               -101.466766
geolocation_city                 * cidade
geolocation_state                      AC
dtype: object

'*' sign in front of the geolocation_city in the geolocation dataset

In [ ]:
#check the maximum number of each column in the dataset
df_geolocation.max()

geolocation_zip_code_prefix         99990
geolocation_lat                 45.065933
geolocation_lng                121.105394
geolocation_city                     óleo
geolocation_state                      TO
dtype: object

In [ ]:
#check whether both latitute and longitude columns have the same number of rows
df_geolocation['geolocation_lat'].value_counts().sum()==df_geolocation['geolocation_lng'].value_counts().sum()

np.True_

In [ ]:
#check the number of unique latitude values in the dataset 
df_geolocation['geolocation_lat'].nunique()

717363

In [ ]:
#check the number of longitude values in the dataset 
df_geolocation['geolocation_lng'].nunique()

717615

In [ ]:
#count the number of records for each city
df_geolocation['geolocation_city'].value_counts()

geolocation_city
sao paulo               135800
rio de janeiro           62151
belo horizonte           27805
são paulo                24918
curitiba                 16593
                         ...  
jacuípe                      1
mar vermelho                 1
quebrangulo                  1
poço das trincheiras         1
poxim                        1
Name: count, Length: 8011, dtype: int64

In [ ]:
#count the number of records for each state
df_geolocation['geolocation_state'].value_counts()

geolocation_state
SP    404268
MG    126336
RJ    121169
RS     61851
PR     57859
SC     38328
BA     36045
GO     20139
ES     16748
PE     16432
DF     12986
MT     12031
CE     11674
PA     10853
MS     10431
MA      7853
PB      5538
RN      5041
PI      4549
AL      4183
TO      3576
SE      3563
RO      3478
AM      2432
AC      1301
AP       853
RR       646
Name: count, dtype: int64

In [ ]:
#count the number of unique records for each city
df_geolocation['geolocation_city'].nunique()

8011

In [ ]:
#count the number of unique records for each state
df_geolocation['geolocation_state'].nunique()

27

In [ ]:
#inspect unique city names
df_geolocation['geolocation_city'].unique()

array(['sao paulo', 'são paulo', 'sao bernardo do campo', ..., 'ciríaco',
       'estação', 'vila lângaro'], dtype=object)

In [ ]:
#inspect unique state names
df_geolocation['geolocation_state'].unique()

array(['SP', 'RN', 'AC', 'RJ', 'ES', 'MG', 'BA', 'SE', 'PE', 'AL', 'PB',
       'CE', 'PI', 'MA', 'PA', 'AP', 'AM', 'RR', 'DF', 'GO', 'RO', 'TO',
       'MT', 'MS', 'RS', 'PR', 'SC'], dtype=object)

**Note:**
A difference in the number of customer cities and the number of geolocaiton cities is observed

## 4.Load and Initial Profiling of 'Order Items Datset'

In [ ]:
#check the shape of the order items dataset
print(f'Order Items Dataset Shape:',df_order_item.shape)
df_order_item.head()

Order Items Dataset Shape: (112650, 7)


,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.90,13.29
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.90,19.93
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,199.00,17.87
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,2018-08-15 10:10:18,12.99,12.79
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2017-02-13 13:57:51,199.90,18.14


In [ ]:
#inspect the dataset structure and data types
df_order_item.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 112650 entries, 0 to 112649
Data columns (total 7 columns):
 #   Column               Non-Null Count   Dtype  
---  ------               --------------   -----  
 0   order_id             112650 non-null  object 
 1   order_item_id        112650 non-null  int64  
 2   product_id           112650 non-null  object 
 3   seller_id            112650 non-null  object 
 4   shipping_limit_date  112650 non-null  object 
 5   price                112650 non-null  float64
 6   freight_value        112650 non-null  float64
dtypes: float64(2), int64(1), object(4)
memory usage: 6.0+ MB


In [ ]:
#check for duplicated rows
df_order_item.duplicated().sum()

np.int64(0)

In [ ]:
#check for missing values
df_order_item.isna().sum()

order_id               0
order_item_id          0
product_id             0
seller_id              0
shipping_limit_date    0
price                  0
freight_value          0
dtype: int64

In [ ]:
#inspect the initial rows of the dataset
df_order_item.head()

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.90,13.29
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.90,19.93
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,199.00,17.87
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,2018-08-15 10:10:18,12.99,12.79
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2017-02-13 13:57:51,199.90,18.14


In [ ]:
#check the minimum price of an order item in the dataset
df_order_item['price'].min()

0.85

In [ ]:
#check the max price of an order item in the dataset
df_order_item['price'].max()

6735.0

In [ ]:
#check if there are errors in order item price in the dataset
(df_order_item['price']<0).sum()

np.int64(0)

In [ ]:
#check the initial values of the freight value column
df_order_item['freight_value'].head()

0    13.29
1    19.93
2    17.87
3    12.79
4    18.14
Name: freight_value, dtype: float64

In [ ]:
#check if there are errors in freight value in the dataset
(df_order_item['freight_value']<0).sum()

np.int64(0)

In [ ]:
#check the minimum freight value
df_order_item['freight_value'].min()

0.0

In [ ]:
#check the max freight value
df_order_item['freight_value'].max()

409.68

In [ ]:
#check the max value of the shipping limit date
df_order_item['shipping_limit_date'].max()

'2020-04-09 22:35:08'

In [ ]:
#check the inital values of the shipping limit date
df_order_item['shipping_limit_date'].head()

0    2017-09-19 09:45:35
1    2017-05-03 11:05:13
2    2018-01-18 14:48:30
3    2018-08-15 10:10:18
4    2017-02-13 13:57:51
Name: shipping_limit_date, dtype: object

In [ ]:
#convert the shipping limit date to datetime data type
df_order_item['shipping_limit_date']=pd.to_datetime(
    df_order_item['shipping_limit_date'],
    errors='coerce'
)

In [ ]:
#check the min hour in the shipping limit date timestamps
df_order_item['shipping_limit_date'].dt.hour.min()

0

In [ ]:
#check the max hour in the shipping limit date timestamps
df_order_item['shipping_limit_date'].dt.hour.max()

23

In [ ]:
#check the min day in the shipping limit date timestamps
df_order_item['shipping_limit_date'].dt.day.min()

1

In [ ]:
#check the max day in the shipping limit date timestamps
df_order_item['shipping_limit_date'].dt.day.max()

31

In [ ]:
#check the min minute in the shipping limit date timestamps
df_order_item['shipping_limit_date'].dt.minute.min()

0

In [ ]:
#check the max minute in the shipping limit date timestamps
df_order_item['shipping_limit_date'].dt.minute.max()

59

In [ ]:
#check the min second in the shipping limit date timestamps
df_order_item['shipping_limit_date'].dt.second.min()

0

In [ ]:
#check the max second in the shipping limit date timestamps
df_order_item['shipping_limit_date'].dt.second.max()

59

In [ ]:
#check the summary statistics of the order id column
df_order_item['order_item_id'].describe()

count    112650.000000
mean          1.197834
std           0.705124
min           1.000000
25%           1.000000
50%           1.000000
75%           1.000000
max          21.000000
Name: order_item_id, dtype: float64

In [ ]:
#check the number of unique order id
df_order_item['order_id'].nunique()

98666

In [ ]:
#check the number of unique order item id
df_order_item['order_item_id'].nunique()

21

In [ ]:
#convert the shipping limit date to datetime data type
df_order_item['shipping_limit_date']=pd.to_datetime(
    df_order_item['shipping_limit_date'],
    errors='coerce'
)

In [ ]:
#inspect min and max values of datetime components for the shipping_limit_date column
time_cols=['date', 'hour', 'minute', 'second']

for time in time_cols:
  print(f'\nTime:', time)
  print(f'Min: ', getattr(df_order_item['shipping_limit_date'].dt, time).min())
  print(f'Max: ', getattr(df_order_item['shipping_limit_date'].dt, time).max())

## 5.Load and Initial Profiling of 'Order Payments Datset'

In [ ]:
#check the shape of the order payments dataset
print(f'Order Payments Dataset Shape:',df_order_payments.shape)
df_order_payments.head()

Order Payments Dataset Shape: (103886, 5)


,order_id,payment_sequential,payment_type,payment_installments,payment_value
0,b81ef226f3fe1789b1e8b2acac839d17,1,credit_card,8,99.33
1,a9810da82917af2d9aefd1278f1dcfa0,1,credit_card,1,24.39
2,25e8ea4e93396b6fa0d3dd708e76c1bd,1,credit_card,1,65.71
3,ba78997921bbcdc1373bb41e913ab953,1,credit_card,8,107.78
4,42fdf880ba16b47b59251dd489d4441a,1,credit_card,2,128.45


In [ ]:
#check the last rows of the dataset
df_order_payments.tail()

,order_id,payment_sequential,payment_type,payment_installments,payment_value
103881,0406037ad97740d563a178ecc7a2075c,1,boleto,1,363.31
103882,7b905861d7c825891d6347454ea7863f,1,credit_card,2,96.80
103883,32609bbb3dd69b3c066a6860554a77bf,1,credit_card,1,47.77
103884,b8b61059626efa996a60be9bb9320e10,1,credit_card,5,369.54
103885,28bbae6599b09d39ca406b747b6632b1,1,boleto,1,191.58


In [ ]:
#inspect the dataset structure and data types
df_order_payments.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 103886 entries, 0 to 103885
Data columns (total 5 columns):
 #   Column                Non-Null Count   Dtype  
---  ------                --------------   -----  
 0   order_id              103886 non-null  object 
 1   payment_sequential    103886 non-null  int64  
 2   payment_type          103886 non-null  object 
 3   payment_installments  103886 non-null  int64  
 4   payment_value         103886 non-null  float64
dtypes: float64(1), int64(2), object(2)
memory usage: 4.0+ MB


In [ ]:
#check for missing values
df_order_payments.isna().sum()

order_id                0
payment_sequential      0
payment_type            0
payment_installments    0
payment_value           0
dtype: int64

In [ ]:
#check for duplicated rows
df_order_payments.duplicated().sum()

np.int64(0)

In [ ]:
#check the number of unique order id in the dataset
df_order_payments['order_id'].nunique()

99440

In [ ]:
#check the number of unique payment types in the dataset
df_order_payments['payment_type'].nunique()

5

In [ ]:
#check the frequency of each payment type in the dataset
df_order_payments['payment_type'].value_counts()

payment_type
credit_card    76795
boleto         19784
voucher         5775
debit_card      1529
not_defined        3
Name: count, dtype: int64

In [ ]:
#count unique payment installment values
df_order_payments['payment_installments'].nunique()

24

In [ ]:
#count the frequency of payment installment values
df_order_payments['payment_installments'].value_counts()

payment_installments
1     52546
2     12413
3     10461
4      7098
10     5328
5      5239
8      4268
6      3920
7      1626
9       644
12      133
15       74
18       27
11       23
24       18
20       17
13       16
14       15
17        8
16        5
21        3
0         2
22        1
23        1
Name: count, dtype: int64

In [ ]:
#check the min installment value
df_order_payments['payment_installments'].min()

0

In [ ]:
#check the max installment value
df_order_payments['payment_installments'].max()

24

In [ ]:
#check the min payment value
df_order_payments['payment_value'].min()

0.0

In [ ]:
#check the max payment value
df_order_payments['payment_value'].max()

13664.08

In [ ]:
#check if the payment value column contain errors
(df_order_payments['payment_value']<0).sum()

np.int64(0)

## 6.Load and Initial Profiling of 'Order Reviews Datset'

In [ ]:
#inspect the shape of the dataset
print(f'Order Reviews Dataset Shape:',df_order_review.shape)
df_order_review.head()

Order Reviews Dataset Shape: (99224, 7)


,review_id,order_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp
0,7bc2406110b926393aa56f80a40eba40,73fc7af87114b39712e6da79b0a377eb,4,NaN,NaN,2018-01-18 00:00:00,2018-01-18 21:46:59
1,80e641a11e56f04c1ad469d5645fdfde,a548910a1c6147796b98fdf73dbeba33,5,NaN,NaN,2018-03-10 00:00:00,2018-03-11 03:05:13
2,228ce5500dc1d8e020d8d1322874b6f0,f9e4b658b201a9f2ecdecbb34bed034b,5,NaN,NaN,2018-02-17 00:00:00,2018-02-18 14:36:24
3,e64fb393e7b32834bb789ff8bb30750e,658677c97b385a9be170737859d3511b,5,NaN,Recebi bem antes do prazo estipulado.,2017-04-21 00:00:00,2017-04-21 22:02:06
4,f7c4243c7fe1938f181bec41a392bdeb,8e6bfb81e283fa7e4f11123a3fb894f1,5,NaN,Parabéns lojas lannister adorei comprar pela I...,2018-03-01 00:00:00,2018-03-02 10:26:53


In [ ]:
#check if the dataset contain missing values
df_order_review.isna().sum()

review_id                      0
order_id                       0
review_score                   0
review_comment_title       87656
review_comment_message     58247
review_creation_date           0
review_answer_timestamp        0
dtype: int64

In [ ]:
#check the num of rows in the dataset
df_order_review.shape[0]

99224

**Note:**

review_comment_title contains 87,656 missing values (~88%) and review_comment_message contains 58,247 missing values (~59%) out of 99,224 total reviews.

This is expected in e-commerce datasets. Customers are typically required to provide a star rating, while written comments and titles are optional, which explains the high proportion of missing textual reviews.


In [ ]:
#check for duplicated rows
df_order_review.duplicated().sum()

np.int64(0)

In [ ]:
#inspect the dataset structure and data types
df_order_review.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99224 entries, 0 to 99223
Data columns (total 7 columns):
 #   Column                   Non-Null Count  Dtype 
---  ------                   --------------  ----- 
 0   review_id                99224 non-null  object
 1   order_id                 99224 non-null  object
 2   review_score             99224 non-null  int64 
 3   review_comment_title     11568 non-null  object
 4   review_comment_message   40977 non-null  object
 5   review_creation_date     99224 non-null  object
 6   review_answer_timestamp  99224 non-null  object
dtypes: int64(1), object(6)
memory usage: 5.3+ MB


In [ ]:
#view the inital rows of the dataset
df_order_review.head()

,review_id,order_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp
0,7bc2406110b926393aa56f80a40eba40,73fc7af87114b39712e6da79b0a377eb,4,NaN,NaN,2018-01-18 00:00:00,2018-01-18 21:46:59
1,80e641a11e56f04c1ad469d5645fdfde,a548910a1c6147796b98fdf73dbeba33,5,NaN,NaN,2018-03-10 00:00:00,2018-03-11 03:05:13
2,228ce5500dc1d8e020d8d1322874b6f0,f9e4b658b201a9f2ecdecbb34bed034b,5,NaN,NaN,2018-02-17 00:00:00,2018-02-18 14:36:24
3,e64fb393e7b32834bb789ff8bb30750e,658677c97b385a9be170737859d3511b,5,NaN,Recebi bem antes do prazo estipulado.,2017-04-21 00:00:00,2017-04-21 22:02:06
4,f7c4243c7fe1938f181bec41a392bdeb,8e6bfb81e283fa7e4f11123a3fb894f1,5,NaN,Parabéns lojas lannister adorei comprar pela I...,2018-03-01 00:00:00,2018-03-02 10:26:53


In [ ]:
#count reviews where both the review title and the seller response timestamp are missing
(df_order_review['review_comment_title'].isna() & df_order_review['review_answer_timestamp'].isna()).sum()

np.int64(0)

In [ ]:
#count reviews where the review title is missing but a response timestamp exists
(df_order_review['review_comment_title'].isna() & df_order_review['review_answer_timestamp'].notna()).sum()

np.int64(87656)

In [ ]:
#count reviews where both the review comment and response timestamp are missing
(df_order_review['review_comment_message'].isna() & df_order_review['review_answer_timestamp'].isna()).sum()

np.int64(0)

In [ ]:
#count reviews where the review comment is missing but a response timestamp exists
(df_order_review['review_comment_message'].isna() & df_order_review['review_answer_timestamp'].notna()).sum()

np.int64(58247)

In [ ]:
#count the number of unique order id
df_order_review['order_id'].nunique()

98673

In [ ]:
#count the number of uniqe review id
df_order_review['review_id'].nunique()

98410

In [ ]:
#view the inital rows of the review answer timestamp column
df_order_review['review_answer_timestamp'].head()

0    2018-01-18 21:46:59
1    2018-03-11 03:05:13
2    2018-02-18 14:36:24
3    2017-04-21 22:02:06
4    2018-03-02 10:26:53
Name: review_answer_timestamp, dtype: object

In [ ]:
#check the min value of the review answer timestamp
df_order_review['review_answer_timestamp'].min()

'2016-10-07 18:32:28'

In [ ]:
#view the inital rows of the review creation date column
df_order_review['review_creation_date'].head()

0    2018-01-18 00:00:00
1    2018-03-10 00:00:00
2    2018-02-17 00:00:00
3    2017-04-21 00:00:00
4    2018-03-01 00:00:00
Name: review_creation_date, dtype: object

In [ ]:
#check the min value of the review creation date column
df_order_review['review_creation_date'].min()

'2016-10-02 00:00:00'

In [ ]:
#convert review timestamp columns to datetime type
order_review_date_cols=['review_creation_date', 'review_answer_timestamp']

for col in order_review_date_cols:
  df_order_review[col]=pd.to_datetime(
      df_order_review[col],
      errors='coerce'
  )

In [ ]:
#inspect min and max values of datetime components in review timestamp columns
for col in order_review_date_cols:
  print(f'\nColumn:', col) 
  for time in time_cols:
    print(f'\nTime:', time)
    print(f'Min: ', getattr(df_order_review[col].dt, time).min())
    print(f'Max: ', getattr(df_order_review[col].dt, time).max())


Column: review_creation_date

Time: date
Min:  2016-10-02
Max:  2018-08-31

Time: hour
Min:  0
Max:  1

Time: minute
Min:  0
Max:  0

Time: second
Min:  0
Max:  0

Column: review_answer_timestamp

Time: date
Min:  2016-10-07
Max:  2018-10-29

Time: hour
Min:  0
Max:  23

Time: minute
Min:  0
Max:  59

Time: second
Min:  0
Max:  59


## 7.Load and Initial Profiling of 'Orders Datset'

In [ ]:
#check the shape of the dataset
print(f'Orders Dataset Shape:',df_orders.shape)
df_orders.head()

Orders Dataset Shape: (99441, 8)


,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15 00:00:00
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26 00:00:00


In [ ]:
#inspect the dataset structure and data types
df_orders.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 8 columns):
 #   Column                         Non-Null Count  Dtype         
---  ------                         --------------  -----         
 0   order_id                       99441 non-null  object        
 1   customer_id                    99441 non-null  object        
 2   order_status                   99441 non-null  object        
 3   order_purchase_timestamp       99441 non-null  datetime64[ns]
 4   order_approved_at              99281 non-null  datetime64[ns]
 5   order_delivered_carrier_date   97658 non-null  datetime64[ns]
 6   order_delivered_customer_date  96476 non-null  datetime64[ns]
 7   order_estimated_delivery_date  99441 non-null  datetime64[ns]
dtypes: datetime64[ns](5), object(3)
memory usage: 6.1+ MB


In [ ]:
#check for missing values
df_orders.isna().sum()

order_id                            0
customer_id                         0
order_status                        0
order_purchase_timestamp            0
order_approved_at                 160
order_delivered_carrier_date     1783
order_delivered_customer_date    2965
order_estimated_delivery_date       0
dtype: int64

**Notes:**

**order_approved_at** : 160 missing

This could occur when:

- Payment was not approved

- The order was cancelled

- The order was expired or failed

Therefore, missing approval timestamps likely correspond to orders that did not progress beyond the payment stage, rather than indicating a data quality issue.

**order_delivered_carrier_date** : 1,783 missing

This could occur when:

- The order was cancelled before shipment

- The order was never handed to a carrier

- The logistics process did not reach the dispatch stage

These missing values likely reflect orders that did not progress to the shipping stage.

**order_delivered_customer_date** : 2,965 missing

This could occur when:

- Orders were cancelled

- Orders were still in transit at the time of data collection

- Orders were undeliverable

In such cases, the delivery process may not have been completed, which explains the missing timestamps.

In [ ]:
#count orders where approval timestamp is missing but the carrier delivery date exists
(df_orders['order_approved_at'].isna()& df_orders['order_delivered_carrier_date'].notna()).sum()

np.int64(14)

**Notes:**

Out of **99,441 orders**, **14 records** contain a delivery carrier timestamp despite a missing approval timestamp.

Given the very small proportion, this likely represents rare edge cases or logging inconsistencies rather than a systemic data quality issue.


In [ ]:
#count orders where approval timestamp is missing but the customer delivery date exists
(df_orders['order_approved_at'].isna()& df_orders['order_delivered_customer_date'].notna()).sum()

np.int64(14)

**Notes:**

Across the orders dataset (**99,441 records**), **14 orders** were identified where delivery timestamps
exist despite a missing approval timestamp.

These same records were consistently observed at both
carrier handoff and customer delivery stages, indicating isolated logging gaps rather than systemic
data quality issues.

In [ ]:
#count orders where the carrier delivery date is missing but the customer delivery date exists
(df_orders['order_delivered_carrier_date'].isna()& df_orders['order_delivered_customer_date'].notna()).sum()

np.int64(1)

**Notes:**

A single order exhibits a customer delivery timestamp without a recorded carrier handoff timestamp.

As it is 1 out of 99,441 orders, this is treated as a rare logging anomaly.


In [ ]:
#check for duplicated values
df_orders.duplicated().sum()

np.int64(0)

In [ ]:
#view the inital rows of the dataset
df_orders.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26


In [ ]:
#check the number of unique order id
df_orders['order_id'].nunique()

99441

In [ ]:
#check the number of unique customer id
df_orders['customer_id'].nunique()

99441

In [ ]:
#check the number of unique order status types
df_orders['order_status'].nunique()

8

In [ ]:
#check the frequency of each order status type
df_orders['order_status'].value_counts()

order_status
delivered      96478
shipped         1107
canceled         625
unavailable      609
invoiced         314
processing       301
created            5
approved           2
Name: count, dtype: int64

In [ ]:
#check the inital rows of the order purchase timestamp column
df_orders['order_purchase_timestamp'].head()

0   2017-10-02 10:56:33
1   2018-07-24 20:41:37
2   2018-08-08 08:38:49
3   2017-11-18 19:28:06
4   2018-02-13 21:18:39
Name: order_purchase_timestamp, dtype: datetime64[ns]

In [ ]:
#check the inital rows of the order approved at column
df_orders['order_approved_at'].head()

0   2017-10-02 11:07:15
1   2018-07-26 03:24:27
2   2018-08-08 08:55:23
3   2017-11-18 19:45:59
4   2018-02-13 22:20:29
Name: order_approved_at, dtype: datetime64[ns]

In [ ]:
#check the inital rows of the order delivered carrier date column
df_orders['order_delivered_carrier_date'].head()

0   2017-10-04 19:55:00
1   2018-07-26 14:31:00
2   2018-08-08 13:50:00
3   2017-11-22 13:39:59
4   2018-02-14 19:46:34
Name: order_delivered_carrier_date, dtype: datetime64[ns]

In [ ]:
#check the inital rows of the order delivered customer date column
df_orders['order_delivered_customer_date'].head()

0   2017-10-10 21:25:13
1   2018-08-07 15:27:45
2   2018-08-17 18:06:29
3   2017-12-02 00:28:42
4   2018-02-16 18:17:02
Name: order_delivered_customer_date, dtype: datetime64[ns]

In [ ]:
#check the inital rows of the order estimated delivery date column
df_orders['order_estimated_delivery_date'].head()

0   2017-10-18
1   2018-08-13
2   2018-09-04
3   2017-12-15
4   2018-02-26
Name: order_estimated_delivery_date, dtype: datetime64[ns]

In [ ]:
#convert order timestamp columns to datetime and inspect min/max values of their datetime components
df_orders_datetime_cols=['order_purchase_timestamp', 'order_approved_at', 'order_delivered_carrier_date', 'order_delivered_customer_date', 'order_estimated_delivery_date']

for col in df_orders_datetime_cols:
  df_orders[col]=pd.to_datetime(
      df_orders[col],
      errors='coerce')

for col in df_orders_datetime_cols:
  print(f'\nColumn:', col) 
  for time in time_cols: 
    print(f'\nTime:', time)
    print(f'Min: ', getattr(df_orders[col].dt, time).dropna().min())
    print(f'Max: ', getattr(df_orders[col].dt, time).dropna().max())


Column: order_purchase_timestamp

Time: date
Min:  2016-09-04
Max:  2018-10-17

Time: hour
Min:  0
Max:  23

Time: minute
Min:  0
Max:  59

Time: second
Min:  0
Max:  59

Column: order_approved_at

Time: date
Min:  2016-09-15
Max:  2018-09-03

Time: hour
Min:  0.0
Max:  23.0

Time: minute
Min:  0.0
Max:  59.0

Time: second
Min:  0.0
Max:  59.0

Column: order_delivered_carrier_date

Time: date
Min:  2016-10-08
Max:  2018-09-11

Time: hour
Min:  0.0
Max:  23.0

Time: minute
Min:  0.0
Max:  59.0

Time: second
Min:  0.0
Max:  59.0

Column: order_delivered_customer_date

Time: date
Min:  2016-10-11
Max:  2018-10-17

Time: hour
Min:  0.0
Max:  23.0

Time: minute
Min:  0.0
Max:  59.0

Time: second
Min:  0.0
Max:  59.0

Column: order_estimated_delivery_date

Time: date
Min:  2016-09-30
Max:  2018-11-12

Time: hour
Min:  0
Max:  0

Time: minute
Min:  0
Max:  0

Time: second
Min:  0
Max:  0


## 8.Load and Initial Profiling of 'Products Datset'

In [ ]:
#check the shape of the dataset
print(f'Products Dataset Shape:',df_products.shape)

Products Dataset Shape: (32951, 9)


In [ ]:
#view the initial rows of the dataset
df_products.head()

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
0,1e9e8ef04dbcff4541ed26657ea517e5,perfumaria,40.0,287.0,1.0,225.0,16.0,10.0,14.0
1,3aa071139cb16b67ca9e5dea641aaa2f,artes,44.0,276.0,1.0,1000.0,30.0,18.0,20.0
2,96bd76ec8810374ed1b65e291975717f,esporte_lazer,46.0,250.0,1.0,154.0,18.0,9.0,15.0
3,cef67bcfe19066a932b7673e239eb23d,bebes,27.0,261.0,1.0,371.0,26.0,4.0,26.0
4,9dc1a7de274444849c219cff195d0b71,utilidades_domesticas,37.0,402.0,4.0,625.0,20.0,17.0,13.0


In [ ]:
#inspect the dataset structure and data types
df_products.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32951 entries, 0 to 32950
Data columns (total 9 columns):
 #   Column                      Non-Null Count  Dtype  
---  ------                      --------------  -----  
 0   product_id                  32951 non-null  object 
 1   product_category_name       32341 non-null  object 
 2   product_name_lenght         32341 non-null  float64
 3   product_description_lenght  32341 non-null  float64
 4   product_photos_qty          32341 non-null  float64
 5   product_weight_g            32949 non-null  float64
 6   product_length_cm           32949 non-null  float64
 7   product_height_cm           32949 non-null  float64
 8   product_width_cm            32949 non-null  float64
dtypes: float64(7), object(2)
memory usage: 2.3+ MB


In [ ]:
#check for missing values
df_products.isna().sum()

product_id                      0
product_category_name         610
product_name_lenght           610
product_description_lenght    610
product_photos_qty            610
product_weight_g                2
product_length_cm               2
product_height_cm               2
product_width_cm                2
dtype: int64

In [ ]:
#check for duplicated rows
df_products.duplicated().sum()

np.int64(0)

In [ ]:
#check for unique product category name
df_products['product_category_name'].unique()

array(['perfumaria', 'artes', 'esporte_lazer', 'bebes',
       'utilidades_domesticas', 'instrumentos_musicais', 'cool_stuff',
       'moveis_decoracao', 'eletrodomesticos', 'brinquedos',
       'cama_mesa_banho', 'construcao_ferramentas_seguranca',
       'informatica_acessorios', 'beleza_saude', 'malas_acessorios',
       'ferramentas_jardim', 'moveis_escritorio', 'automotivo',
       'eletronicos', 'fashion_calcados', 'telefonia', 'papelaria',
       'fashion_bolsas_e_acessorios', 'pcs', 'casa_construcao',
       'relogios_presentes', 'construcao_ferramentas_construcao',
       'pet_shop', 'eletroportateis', 'agro_industria_e_comercio', nan,
       'moveis_sala', 'sinalizacao_e_seguranca', 'climatizacao',
       'consoles_games', 'livros_interesse_geral',
       'construcao_ferramentas_ferramentas',
       'fashion_underwear_e_moda_praia', 'fashion_roupa_masculina',
       'moveis_cozinha_area_de_servico_jantar_e_jardim',
       'industria_comercio_e_negocios', 'telefonia_fixa',
   

In [ ]:
#check for the number of unique product category names
df_products['product_category_name'].nunique()

73

In [ ]:
#check the summary statistics of the product_weight_g column
df_products['product_weight_g'].describe()

count    32949.000000
mean      2276.472488
std       4282.038731
min          0.000000
25%        300.000000
50%        700.000000
75%       1900.000000
max      40425.000000
Name: product_weight_g, dtype: float64

In [ ]:
#check the summary statistics of the product_length_cm column
df_products['product_length_cm'].describe()

count    32949.000000
mean        30.815078
std         16.914458
min          7.000000
25%         18.000000
50%         25.000000
75%         38.000000
max        105.000000
Name: product_length_cm, dtype: float64

In [ ]:
#check the summary statistics of the product_width_cm column
df_products['product_width_cm'].describe()

count    32949.000000
mean        23.196728
std         12.079047
min          6.000000
25%         15.000000
50%         20.000000
75%         30.000000
max        118.000000
Name: product_width_cm, dtype: float64

## 9.Load and Initial Profiling of 'Sellers Datset'

In [ ]:
#check the shape of the dataset
print(f'Sellers Dataset Shape:',df_sellers.shape)

Sellers Dataset Shape: (3095, 4)


In [ ]:
#view the inital rows of the dataset
df_sellers.head()

,seller_id,seller_zip_code_prefix,seller_city,seller_state
0,3442f8959a84dea7ee197c632cb2df15,13023,campinas,SP
1,d1b65fc7debc3361ea86b5f14c68d2e2,13844,mogi guacu,SP
2,ce3ad9de960102d0677a81f5d0bb7b2d,20031,rio de janeiro,RJ
3,c0f3eea2e14555b6faeea3dd58c1b1c3,4195,sao paulo,SP
4,51a04a8a6bdcb23deccc82b0b80742cf,12914,braganca paulista,SP


In [ ]:
#inspect the dataset structure and data types
df_sellers.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3095 entries, 0 to 3094
Data columns (total 4 columns):
 #   Column                  Non-Null Count  Dtype 
---  ------                  --------------  ----- 
 0   seller_id               3095 non-null   object
 1   seller_zip_code_prefix  3095 non-null   int64 
 2   seller_city             3095 non-null   object
 3   seller_state            3095 non-null   object
dtypes: int64(1), object(3)
memory usage: 96.8+ KB


- **seller_zip_code_prefix**  
  The postal code prefix indicating the seller’s geographic region.


In [ ]:
#check for missing values
df_sellers.isna().sum()

seller_id                 0
seller_zip_code_prefix    0
seller_city               0
seller_state              0
dtype: int64

In [ ]:
#check for duplicated rows
df_sellers.duplicated().sum()

np.int64(0)

In [ ]:
#check for the number of unique seller id
df_sellers['seller_id'].nunique()

3095

In [ ]:
#check for the number of unique seller_zip_code_prefix
df_sellers['seller_zip_code_prefix'].nunique()

2246

In [ ]:
#check the frequency of unique seller_zip_code_prefix
df_sellers['seller_zip_code_prefix'].value_counts()

seller_zip_code_prefix
14940    49
13660    10
13920     9
16200     9
87050     8
         ..
83707     1
85065     1
78552     1
3632      1
12051     1
Name: count, Length: 2246, dtype: int64

In [ ]:
#check for the number of unique seller cities
df_sellers['seller_city'].nunique()

611

In [ ]:
#check the frequency of each seller city
df_sellers['seller_city'].value_counts()

seller_city
sao paulo              694
curitiba               127
rio de janeiro          96
belo horizonte          68
ribeirao preto          52
                      ... 
taruma                   1
s jose do rio preto      1
domingos martins         1
messias targino          1
leme                     1
Name: count, Length: 611, dtype: int64

In [ ]:
#check the number of unique seller state
df_sellers['seller_state'].nunique()

23

In [ ]:
#check the frequency of seller state
df_sellers['seller_state'].value_counts()

seller_state
SP    1849
PR     349
MG     244
SC     190
RJ     171
RS     129
GO      40
DF      30
ES      23
BA      19
CE      13
PE       9
PB       6
RN       5
MS       5
MT       4
RO       2
SE       2
PI       1
AC       1
MA       1
AM       1
PA       1
Name: count, dtype: int64

In [ ]:
#check the number of unique seller zip code grouped by state
df_sellers.groupby('seller_state')['seller_zip_code_prefix'].nunique()

seller_state
AC       1
AM       1
BA      17
CE      13
DF      29
ES      23
GO      35
MA       1
MG     180
MS       5
MT       4
PA       1
PB       6
PE       9
PI       1
PR     219
RJ     138
RN       5
RO       2
RS     105
SC     134
SE       2
SP    1333
Name: seller_zip_code_prefix, dtype: int64

In [ ]:
#check the number of unique sellercity grouped by state
df_sellers.groupby('seller_state')['seller_city'].nunique()

seller_state
AC      1
AM      1
BA     12
CE      7
DF      3
ES     11
GO     12
MA      1
MG     82
MS      2
MT      3
PA      1
PB      5
PE      4
PI      1
PR     67
RJ     38
RN      4
RO      2
RS     51
SC     65
SE      2
SP    261
Name: seller_city, dtype: int64

## 10.Load and Initial Profiling of 'Product Cateogry Name Datset'

In [ ]:
#check the shape of the dataset
print(f'Product Category Dataset Shape:',df_product_category.shape)

Product Category Dataset Shape: (71, 2)


In [ ]:
#view the inital rows of the dataste
df_product_category.head()

,product_category_name,product_category_name_english
0,beleza_saude,health_beauty
1,informatica_acessorios,computers_accessories
2,automotivo,auto
3,cama_mesa_banho,bed_bath_table
4,moveis_decoracao,furniture_decor


In [ ]:
#inspect the dataset structure and data types
df_product_category.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 71 entries, 0 to 70
Data columns (total 2 columns):
 #   Column                         Non-Null Count  Dtype 
---  ------                         --------------  ----- 
 0   product_category_name          71 non-null     object
 1   product_category_name_english  71 non-null     object
dtypes: object(2)
memory usage: 1.2+ KB


In [ ]:
#check for missing values
df_product_category.isna().sum()

product_category_name            0
product_category_name_english    0
dtype: int64

In [ ]:
#check for duplicated rows
df_product_category.duplicated().sum()

np.int64(0)

In [ ]:
#check the number of unique product_category_name_english
df_product_category['product_category_name_english'].nunique()

71

In [ ]:
#check the frequency of each unique product_category_name_english
df_product_category['product_category_name_english'].value_counts()

product_category_name_english
health_beauty                1
food                         1
fashion_sport                1
fashion_underwear_beach      1
construction_tools_safety    1
                            ..
luggage_accessories          1
cool_stuff                   1
fashion_shoes                1
audio                        1
security_and_services        1
Name: count, Length: 71, dtype: int64

In [ ]:
#inspect the unique values of product_category_name_english
df_product_category['product_category_name_english'].unique()

array(['health_beauty', 'computers_accessories', 'auto', 'bed_bath_table',
       'furniture_decor', 'sports_leisure', 'perfumery', 'housewares',
       'telephony', 'watches_gifts', 'food_drink', 'baby', 'stationery',
       'tablets_printing_image', 'toys', 'fixed_telephony',
       'garden_tools', 'fashion_bags_accessories', 'small_appliances',
       'consoles_games', 'audio', 'fashion_shoes', 'cool_stuff',
       'luggage_accessories', 'air_conditioning',
       'construction_tools_construction',
       'kitchen_dining_laundry_garden_furniture',
       'costruction_tools_garden', 'fashion_male_clothing', 'pet_shop',
       'office_furniture', 'market_place', 'electronics',
       'home_appliances', 'party_supplies', 'home_confort',
       'costruction_tools_tools', 'agro_industry_and_commerce',
       'furniture_mattress_and_upholstery', 'books_technical',
       'home_construction', 'musical_instruments',
       'furniture_living_room', 'construction_tools_lights',
       'indust

# Step 4 - Data Cleaning

In [346]:
#merge the english category names for the df_products dataframe
df_products=df_products.merge(
    df_product_category,
    on='product_category_name',
    how='left')

In [347]:
df_products.shape

(32951, 10)

In [ ]:
order_review_date_cols=['review_creation_date', 'review_answer_timestamp']

for col in order_review_date_cols:
  df_order_review[col]=pd.to_datetime(
      df_order_review[col],
      errors='coerce'
  )

In [ ]:
time_cols=['date', 'hour', 'minute', 'second']
for col in order_review_date_cols:
  print(f'\nColumn:', col) 
  for time in time_cols:
    print(f'\nTime:', time)
    print(f'Min: ', getattr(df_order_review[col].dt, time).min())
    print(f'Max: ', getattr(df_order_review[col].dt, time).max())


Column: review_creation_date

Time: date
Min:  2016-10-02
Max:  2018-08-31

Time: hour
Min:  0
Max:  1

Time: minute
Min:  0
Max:  0

Time: second
Min:  0
Max:  0

Column: review_answer_timestamp

Time: date
Min:  2016-10-07
Max:  2018-10-29

Time: hour
Min:  0
Max:  23

Time: minute
Min:  0
Max:  59

Time: second
Min:  0
Max:  59


In [ ]:
time_cols=['date', 'hour', 'minute', 'second']
for col in order_review_date_cols:
  print(f'\nColumn:', col) 
  for time in time_cols:
    print(f'\nTime:', time)
    print(f'Min: ', getattr(df_order_review[col].dt, time).min())
    print(f'Max: ', getattr(df_order_review[col].dt, time).max())


Column: review_creation_date

Time: date
Min:  2016-10-02
Max:  2018-08-31

Time: hour
Min:  0
Max:  1

Time: minute
Min:  0
Max:  0

Time: second
Min:  0
Max:  0

Column: review_answer_timestamp

Time: date
Min:  2016-10-07
Max:  2018-10-29

Time: hour
Min:  0
Max:  23

Time: minute
Min:  0
Max:  59

Time: second
Min:  0
Max:  59


In [ ]:
#convert the shipping limit date to datetime data type
df_order_item['shipping_limit_date']=pd.to_datetime(
    df_order_item['shipping_limit_date'],
    errors='coerce'
)

In [ ]:
for time in time_cols:
  print(f'\nTime:', time)
  print(f'Min: ', getattr(df_order_item['shipping_limit_date'].dt, time).min())
  print(f'Max: ', getattr(df_order_item['shipping_limit_date'].dt, time).max())

In [348]:
#normalise and convert the data type of categorical cols into category

df_orders['order_status']=(
    df_orders['order_status']
    .str.strip()
    .str.lower()
    .astype('category')
)

df_order_payments['payment_type']=(
    df_order_payments['payment_type']
    .str.strip()
    .str.lower()
    .astype('category')
)

In [349]:
df_orders.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 8 columns):
 #   Column                         Non-Null Count  Dtype         
---  ------                         --------------  -----         
 0   order_id                       99441 non-null  object        
 1   customer_id                    99441 non-null  object        
 2   order_status                   99441 non-null  category      
 3   order_purchase_timestamp       99441 non-null  datetime64[ns]
 4   order_approved_at              99281 non-null  datetime64[ns]
 5   order_delivered_carrier_date   97658 non-null  datetime64[ns]
 6   order_delivered_customer_date  96476 non-null  datetime64[ns]
 7   order_estimated_delivery_date  99441 non-null  datetime64[ns]
dtypes: category(1), datetime64[ns](5), object(2)
memory usage: 5.4+ MB


In [350]:
df_order_payments['payment_type'].info()

<class 'pandas.core.series.Series'>
RangeIndex: 103886 entries, 0 to 103885
Series name: payment_type
Non-Null Count   Dtype   
--------------   -----   
103886 non-null  category
dtypes: category(1)
memory usage: 101.8 KB


In [351]:
#add revenue column to df_order_item
df_order_item['item_revenue']=df_order_item['price']

In [352]:
df_order_item.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 112650 entries, 0 to 112649
Data columns (total 8 columns):
 #   Column               Non-Null Count   Dtype         
---  ------               --------------   -----         
 0   order_id             112650 non-null  object        
 1   order_item_id        112650 non-null  int64         
 2   product_id           112650 non-null  object        
 3   seller_id            112650 non-null  object        
 4   shipping_limit_date  112650 non-null  datetime64[ns]
 5   price                112650 non-null  float64       
 6   freight_value        112650 non-null  float64       
 7   item_revenue         112650 non-null  float64       
dtypes: datetime64[ns](1), float64(3), int64(1), object(3)
memory usage: 6.9+ MB


In [353]:
#add freight value cost col for each order item in the order
df_order_item['item_freight_cost']=df_order_item['freight_value']

In [354]:
df_orders.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 8 columns):
 #   Column                         Non-Null Count  Dtype         
---  ------                         --------------  -----         
 0   order_id                       99441 non-null  object        
 1   customer_id                    99441 non-null  object        
 2   order_status                   99441 non-null  category      
 3   order_purchase_timestamp       99441 non-null  datetime64[ns]
 4   order_approved_at              99281 non-null  datetime64[ns]
 5   order_delivered_carrier_date   97658 non-null  datetime64[ns]
 6   order_delivered_customer_date  96476 non-null  datetime64[ns]
 7   order_estimated_delivery_date  99441 non-null  datetime64[ns]
dtypes: category(1), datetime64[ns](5), object(2)
memory usage: 5.4+ MB


In [355]:
df_customers.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 5 columns):
 #   Column                    Non-Null Count  Dtype 
---  ------                    --------------  ----- 
 0   customer_id               99441 non-null  object
 1   customer_unique_id        99441 non-null  object
 2   customer_zip_code_prefix  99441 non-null  int64 
 3   customer_city             99441 non-null  object
 4   customer_state            99441 non-null  object
dtypes: int64(1), object(4)
memory usage: 3.8+ MB


In [356]:
#create orders_customers_df by merging customer info into orders

orders_customer_df=df_orders.merge(
    df_customers[['customer_id', 'customer_unique_id', 'customer_zip_code_prefix']],
    on='customer_id',
    how='left'
)

In [357]:
orders_customer_df.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,customer_unique_id,customer_zip_code_prefix
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18,7c396fd4830fd04220f754e42b4e5bff,3149
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13,af07308b275d755c9edb36a90c618231,47813
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04,3a653a41f6f9fc3d2a113cf8398680e8,75265
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15,7c142cf63193a1473d2e66489a9ae977,59296
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26,72632f0f9dd73dfee390c9b22eb56dd6,9195


In [358]:
orders_customer_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 10 columns):
 #   Column                         Non-Null Count  Dtype         
---  ------                         --------------  -----         
 0   order_id                       99441 non-null  object        
 1   customer_id                    99441 non-null  object        
 2   order_status                   99441 non-null  category      
 3   order_purchase_timestamp       99441 non-null  datetime64[ns]
 4   order_approved_at              99281 non-null  datetime64[ns]
 5   order_delivered_carrier_date   97658 non-null  datetime64[ns]
 6   order_delivered_customer_date  96476 non-null  datetime64[ns]
 7   order_estimated_delivery_date  99441 non-null  datetime64[ns]
 8   customer_unique_id             99441 non-null  object        
 9   customer_zip_code_prefix       99441 non-null  int64         
dtypes: category(1), datetime64[ns](5), int64(1), object(3)
memory usage: 6.9+ MB


In [359]:
#add a new col that contain the duration (in days) of the delivery from purchased date to delivered date
df_orders['delivery_duration_days']=(df_orders['order_delivered_customer_date']-df_orders['order_purchase_timestamp']).dt.days

In [360]:
df_orders['delivery_duration_days'].head()

0     8.0
1    13.0
2     9.0
3    13.0
4     2.0
Name: delivery_duration_days, dtype: float64

In [361]:
#add a new col that flags late delivery orders
df_orders['is_late_delivery']=df_orders['order_delivered_customer_date']>df_orders['order_estimated_delivery_date']

In [362]:
df_orders['is_late_delivery'].head()

0    False
1    False
2    False
3    False
4    False
Name: is_late_delivery, dtype: bool

In [363]:
df_orders['order_status'].unique()

['delivered', 'invoiced', 'shipped', 'processing', 'unavailable', 'canceled', 'created', 'approved']
Categories (8, object): ['approved', 'canceled', 'created', 'delivered', 'invoiced', 'processing', 'shipped', 'unavailable']

In [364]:
#create a new col that flages failed orders
df_orders['is_failed_order']=df_orders['order_status'].isin(
    ['unavailable', 'canceled']
)

In [365]:
df_orders.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 11 columns):
 #   Column                         Non-Null Count  Dtype         
---  ------                         --------------  -----         
 0   order_id                       99441 non-null  object        
 1   customer_id                    99441 non-null  object        
 2   order_status                   99441 non-null  category      
 3   order_purchase_timestamp       99441 non-null  datetime64[ns]
 4   order_approved_at              99281 non-null  datetime64[ns]
 5   order_delivered_carrier_date   97658 non-null  datetime64[ns]
 6   order_delivered_customer_date  96476 non-null  datetime64[ns]
 7   order_estimated_delivery_date  99441 non-null  datetime64[ns]
 8   delivery_duration_days         96476 non-null  float64       
 9   is_late_delivery               99441 non-null  bool          
 10  is_failed_order                99441 non-null  bool          
dtypes: bool(2), cat

In [366]:
df_order_item.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 112650 entries, 0 to 112649
Data columns (total 9 columns):
 #   Column               Non-Null Count   Dtype         
---  ------               --------------   -----         
 0   order_id             112650 non-null  object        
 1   order_item_id        112650 non-null  int64         
 2   product_id           112650 non-null  object        
 3   seller_id            112650 non-null  object        
 4   shipping_limit_date  112650 non-null  datetime64[ns]
 5   price                112650 non-null  float64       
 6   freight_value        112650 non-null  float64       
 7   item_revenue         112650 non-null  float64       
 8   item_freight_cost    112650 non-null  float64       
dtypes: datetime64[ns](1), float64(4), int64(1), object(3)
memory usage: 7.7+ MB


In [367]:
df_order_item_enriched=df_order_item.merge(
    df_orders[['order_id', 'order_status', 'delivery_duration_days', 'is_late_delivery', 'is_failed_order']],
    on='order_id',
    how='left'
)

In [368]:
df_order_item_enriched.head()

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value,item_revenue,item_freight_cost,order_status,delivery_duration_days,is_late_delivery,is_failed_order
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.90,13.29,58.90,13.29,delivered,7.0,False,False
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.90,19.93,239.90,19.93,delivered,16.0,False,False
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,199.00,17.87,199.00,17.87,delivered,7.0,False,False
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,2018-08-15 10:10:18,12.99,12.79,12.99,12.79,delivered,6.0,False,False
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2017-02-13 13:57:51,199.90,18.14,199.90,18.14,delivered,25.0,False,False


In [369]:
df_order_item_enriched.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 112650 entries, 0 to 112649
Data columns (total 13 columns):
 #   Column                  Non-Null Count   Dtype         
---  ------                  --------------   -----         
 0   order_id                112650 non-null  object        
 1   order_item_id           112650 non-null  int64         
 2   product_id              112650 non-null  object        
 3   seller_id               112650 non-null  object        
 4   shipping_limit_date     112650 non-null  datetime64[ns]
 5   price                   112650 non-null  float64       
 6   freight_value           112650 non-null  float64       
 7   item_revenue            112650 non-null  float64       
 8   item_freight_cost       112650 non-null  float64       
 9   order_status            112650 non-null  category      
 10  delivery_duration_days  110196 non-null  float64       
 11  is_late_delivery        112650 non-null  bool          
 12  is_failed_order         112650

In [192]:
df_geolocation.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000163 entries, 0 to 1000162
Data columns (total 5 columns):
 #   Column                       Non-Null Count    Dtype  
---  ------                       --------------    -----  
 0   geolocation_zip_code_prefix  1000163 non-null  int64  
 1   geolocation_lat              1000163 non-null  float64
 2   geolocation_lng              1000163 non-null  float64
 3   geolocation_city             1000163 non-null  object 
 4   geolocation_state            1000163 non-null  object 
dtypes: float64(2), int64(1), object(2)
memory usage: 38.2+ MB


In [370]:
#aggregate average latitude and longitude by zip code
geo_agg_df=(
    df_geolocation
    .groupby('geolocation_zip_code_prefix', as_index=False)
    .agg(
        lat=('geolocation_lat', 'mean'),
        lng=('geolocation_lng', 'mean'),
    )
  )

#merge aggregated geolocation into customers DataFrame
df_customers=df_customers.merge(
    geo_agg_df,
    left_on='customer_zip_code_prefix',
    right_on='geolocation_zip_code_prefix',
    how='left'
)

#merge aggregated geolocation into sellers DataFrame
df_sellers=df_sellers.merge(
    geo_agg_df,
    left_on='seller_zip_code_prefix',
    right_on='geolocation_zip_code_prefix',
    how='left'
)

In [371]:
geo_agg_df.head()

,geolocation_zip_code_prefix,lat,lng
0,1001,-23.550190,-46.634024
1,1002,-23.548146,-46.634979
2,1003,-23.548994,-46.635731
3,1004,-23.549799,-46.634757
4,1005,-23.549456,-46.636733


In [195]:
df_customers.head()

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state,geolocation_zip_code_prefix,lat,lng
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,franca,SP,14409.0,-20.498489,-47.396929
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,9790,sao bernardo do campo,SP,9790.0,-23.727992,-46.542848
2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,1151,sao paulo,SP,1151.0,-23.531642,-46.656289
3,b2b6027bc5c5109e529d4dc6358b12c3,259dac757896d24d7702b9acbbff3f3c,8775,mogi das cruzes,SP,8775.0,-23.499702,-46.185233
4,4f2d8ab171c80ec8364f7c12e35b23ad,345ecd01c38d18a9036ed96c73b8d066,13056,campinas,SP,13056.0,-22.975100,-47.142925


In [ ]:
df_customers.info()

In [ ]:
df_sellers.head()

In [ ]:
df_sellers.info()

# Data Quality Validation

In [ ]:
#pip install great_expectations

Start Great Expectations so I can use it.

In [372]:
#import great expectations and give it a short name 'gx'
import great_expectations as gx

#create a gx context
context=gx.get_context()

In [ ]:
#retrieve the data source
data_source_name = "orders_ds"
data_source=context.data_sources.add_pandas(name=data_source_name)

In [373]:
df_orders.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 11 columns):
 #   Column                         Non-Null Count  Dtype         
---  ------                         --------------  -----         
 0   order_id                       99441 non-null  object        
 1   customer_id                    99441 non-null  object        
 2   order_status                   99441 non-null  category      
 3   order_purchase_timestamp       99441 non-null  datetime64[ns]
 4   order_approved_at              99281 non-null  datetime64[ns]
 5   order_delivered_carrier_date   97658 non-null  datetime64[ns]
 6   order_delivered_customer_date  96476 non-null  datetime64[ns]
 7   order_estimated_delivery_date  99441 non-null  datetime64[ns]
 8   delivery_duration_days         96476 non-null  float64       
 9   is_late_delivery               99441 non-null  bool          
 10  is_failed_order                99441 non-null  bool          
dtypes: bool(2), cat

In [375]:
df_orders['delivery_duration_days'].max()

209.0

In [376]:
df_orders.isna().sum()

order_id                            0
customer_id                         0
order_status                        0
order_purchase_timestamp            0
order_approved_at                 160
order_delivered_carrier_date     1783
order_delivered_customer_date    2965
order_estimated_delivery_date       0
delivery_duration_days           2965
is_late_delivery                    0
is_failed_order                     0
dtype: int64

In [ ]:
data_asset_name='orders'
orders_asset=data_source.add_dataframe_asset(name=data_asset_name)

In [ ]:
batch_def_name = 'orders_batch'
orders_batch_def = orders_asset.add_batch_definition_whole_dataframe(
    batch_def_name
)

In [ ]:
batch_parameters = {"dataframe": df_orders}
batch = orders_batch_def.get_batch(batch_parameters=batch_parameters)

In [ ]:
suite = gx.ExpectationSuite(name="inventory_parts_suite")


In [ ]:
suite.add_expectation(
    gx.expectations.ExpectColumnValuesToNotBeNull(
        column="order_id"
    )
)


In [ ]:
# order_id should be unique (this IS correct)
suite.add_expectation(
    gx.expectations.ExpectColumnValuesToBeUnique(
        column="order_id"
    )
)

In [ ]:
suite.add_expectation(
    gx.expectations.ExpectColumnValuesToNotBeNull(
        column="customer_id"
    )
)

suite.add_expectation(
    gx.expectations.ExpectColumnValuesToNotBeNull(
        column="order_estimated_delivery_date"
    )
)

for col in [
    'order_purchase_timestamp'
    "order_approved_at",
    "order_delivered_carrier_date",
    "order_delivered_customer_date",
    'order_estimated_delivery_date'
]:
    suite.add_expectation(
        gx.expectations.ExpectColumnValuesToBeOfType(
            column=col,
            type_="datetime64[ns]"
        )
    )

suite.add_expectation(
    gx.expectations.ExpectColumnValuesToBeBetween(
        column="delivery_duration_days",
        min_value=0,
        mostly=0.97
    )
)

suite.add_expectation(
    gx.expectations.ExpectColumnValuesToBeInSet(
        column="is_late_delivery",
        value_set=[True, False]
    )
)

suite.add_expectation(
    gx.expectations.ExpectColumnValuesToBeInSet(
        column="is_failed_order",
        value_set=[True, False]
    )
)


In [ ]:
# order_status must be one of known states
suite.add_expectation(
    gx.expectations.ExpectColumnValuesToBeInSet(
        column="order_status",
        value_set=[
            "delivered",
            "shipped",
            "canceled",
            "processing",
            "invoiced",
            "unavailable",
            'created',
            'approved'
        ]
    )
)


In [ ]:
# purchase timestamp should exist
suite.add_expectation(
    gx.expectations.ExpectColumnValuesToNotBeNull(
        column="order_purchase_timestamp"
    )
)

In [ ]:
# 4. Register suite
context.suites.add(suite)

In [ ]:
df_orders['order_status'].unique()

In [ ]:
suite = context.suites.get("inventory_parts_suite")


In [ ]:
# 5. Validate
results = batch.validate(suite)
results

In [ ]:
df_order_item.info()

In [ ]:
df_order_item['item_revenue'].min()

In [ ]:
#order_items

order_items_asset=data_source.add_dataframe_asset(name='order_items')

order_items_batch_def=order_items_asset.add_batch_definition_whole_dataframe('order_items_batch')

order_items_batch=order_items_batch_def.get_batch(batch_parameters={'dataframe':df_order_item})

order_items_suite=gx.ExpectationSuite(name='order_items_suite')

In [ ]:
order_items_suite.add_expectation(
    gx.expectations.ExpectColumnValuesToNotBeNull(
        column='order_id'
    )
)

order_items_suite.add_expectation(
    gx.expectations.ExpectColumnValuesToNotBeNull(
        column='order_item_id'
    )
)

order_items_suite.add_expectation(
    gx.expectations.ExpectColumnValuesToBeBetween(
        column='order_item_id',
        min_value=1,
    )
)

order_items_suite.add_expectation(
    gx.expectations.ExpectColumnValuesToNotBeNull(
        column='price',
     )
)

order_items_suite.add_expectation(
    gx.expectations.ExpectColumnValuesToBeBetween(
        column='price',
        min_value=0
     )
)

order_items_suite.add_expectation(
    gx.expectations.ExpectColumnValuesToBeBetween(
        column='freight_value',
        min_value=0
     )
)

order_items_suite.add_expectation(
    gx.expectations.ExpectColumnValuesToNotBeNull(
        column='freight_value',
     )
)

order_items_suite.add_expectation(
    gx.expectations.ExpectColumnValuesToNotBeNull(
        column='item_freight_cost',
     )
)

order_items_suite.add_expectation(
    gx.expectations.ExpectColumnValuesToBeBetween(
        column='item_freight_cost',
        min_value=0
     )
)


order_items_suite.add_expectation(
    gx.expectations.ExpectColumnValuesToNotBeNull(
        column='item_revenue',
     )
)

order_items_suite.add_expectation(
    gx.expectations.ExpectColumnValuesToBeBetween(
        column='item_revenue',
        min_value=0
     )
)

order_items_suite.add_expectation(
    gx.expectations.ExpectColumnPairValuesToBeEqual(
        column_A='item_revenue',
        column_B='price',
     )
)

order_items_suite.add_expectation(
    gx.expectations.ExpectColumnPairValuesToBeEqual(
        column_A='item_freight_cost',
        column_B='freight_value',
     )
)

order_items_suite.add_expectation(
    gx.expectations.ExpectColumnValuesToNotBeNull(
        column='shipping_limit_date',
    )
)

order_items_suite.add_expectation(
    gx.expectations.ExpectColumnValuesToBeOfType(
        column='shipping_limit_date',
        type_='datetime64[ns]'
    )
)

order_items_suite.add_expectation(
    gx.expectations.ExpectColumnValuesToBeUnique(
        column_list=['order_id', 'order_item_id']
    )
)

In [ ]:
context.suites.add(order_items_suite)

In [ ]:
order_items_results=order_items_batch.validate(order_items_suite)

order_items_results

In [ ]:
df_customers.info()

In [ ]:
customers_asset=data_source.add_dataframe_asset(
    name='customers'
)

customers_batch_def=customers_asset.add_batch_definition_whole_dataframe('customers_batch')

customers_batch=customers_batch_def.get_batch(batch_parameters={'dataframe':df_customers})

customers_suite=gx.ExpectationSuite(name='customers_suite')


In [ ]:
# customer_id must not be null
customers_suite.add_expectation(
    gx.expectations.ExpectColumnValuesToNotBeNull(
        column='customer_id'
    )
)

# customer_id must be unique
customers_suite.add_expectation(
    gx.expectations.ExpectColumnValuesToBeUnique(
        column='customer_id'
    )
)

# customer_unique_id must not be null
customers_suite.add_expectation(
    gx.expectations.ExpectColumnValuesToNotBeNull(
        column='customer_unique_id'
    )
)

customers_suite.add_expectation(
    gx.expectations.ExpectColumnValueLengthsToBeBetween(
        column='customer_zip_code_prefix',
        min_value=1,
        mostly=0.997,
    )
)

customers_suite.add_expectation(
    gx.expectations.ExpectColumnValuesToNotBeNull(
        column='customer_state'
    )
)

customers_suite.add_expectation(
    gx.expectations.ExpectColumnValueLengthsToBeBetween(
        column='customer_state',
        min_value=2,
        max_value=2,
    )
)

customers_suite.add_expectation(
    gx.expectations.ExpectColumnValueLengthsToBeBetween(
        column='lat',
        min_value=-90,
        max_value=90,
        mostly=0.997
    )
)

customers_suite.add_expectation(
    gx.expectations.ExpectColumnValueLengthsToBeBetween(
        column='lng',
        min_value=-180,
        max_value=180,
        mostly=0.997
    )
)

In [ ]:
context.suites.add(customers_suite)

In [ ]:
customers_results=customers_batch.validate(customers_suite)

customers_results

In [ ]:
df_geolocation.info()

In [ ]:
df_geolocation['geolocation_zip_code_prefix'].min()

In [ ]:
geolocation_asset=data_source.add_dataframe_asset(
    name='geolocation'
)

geolocation_batch_def=geolocation_asset.add_batch_definition_whole_dataframe('geolocation_batch')

geolocation_batch=geolocation_batch_def.get_batch(batch_parameters={'dataframe':df_geolocation})

geolocation_suite=gx.ExpectationSuite(name='geolocation_suite')


In [ ]:
geolocation_suite.add_expectation(
    gx.expectations.ExpectColumnValuesToNotBeNull(
        column="geolocation_zip_code_prefix"
    )
)

geolocation_suite.add_expectation(
    gx.expectations.ExpectColumnValuesToBeBetween(
        column="geolocation_zip_code_prefix",
        min_value=1
    )
)

geolocation_suite.add_expectation(
    gx.expectations.ExpectColumnValuesToBeBetween(
        column="geolocation_lat",
        min_value=-90,
        max_value=90
    )
)

geolocation_suite.add_expectation(
    gx.expectations.ExpectColumnValuesToBeBetween(
        column="geolocation_lng",
        min_value=-180,
        max_value=180
    )
)

geolocation_suite.add_expectation(
    gx.expectations.ExpectColumnValuesToNotBeNull(
        column="geolocation_state"
    )
)

geolocation_suite.add_expectation(
    gx.expectations.ExpectColumnValueLengthsToBeBetween(
        column="geolocation_state",
        min_value=2,
        max_value=2
    )
)

geolocation_suite.add_expectation(
    gx.expectations.ExpectColumnValuesToNotBeNull(
        column="geolocation_city"
    )
)

In [ ]:
context.suites.add(geolocation_suite)

In [ ]:
geolocation_results=geolocation_batch.validate(geolocation_suite)

geolocation_results

In [ ]:
df_order_review.info()

In [ ]:
df_order_review.isna().sum()

In [ ]:
order_review_asset=data_source.add_dataframe_asset(
    name='order_review'
)

order_review_batch_def=order_review_asset.add_batch_definition_whole_dataframe('order_review_batch')

order_review_batch=order_review_batch_def.get_batch(batch_parameters={'dataframe':df_order_review})

order_review_suite=gx.ExpectationSuite(name='order_review_suite')


In [ ]:
order_review_suite.add_expectation(
    gx.expectations.ExpectColumnValuesToNotBeNull(
        column="review_id"
    )
)

order_review_suite.add_expectation(
    gx.expectations.ExpectColumnValuesToNotBeNull(
        column="order_id"
    )
)

order_review_suite.add_expectation(
    gx.expectations.ExpectColumnValuesToBeBetween(
        column="review_score",
        min_value=1,
        max_value=5
    )
)

order_review_suite.add_expectation(
    gx.expectations.ExpectColumnValuesToNotBeNull(
        column="review_creation_date"
    )
)

order_review_suite.add_expectation(
    gx.expectations.ExpectColumnValuesToNotBeNull(
        column="review_answer_timestamp"
    )
)

order_review_suite.add_expectation(
    gx.expectations.ExpectColumnValuesToBeOfType(
        column="review_creation_date",
        type_="datetime64[ns]"
    )
)

order_review_suite.add_expectation(
    gx.expectations.ExpectColumnValuesToBeOfType(
        column="review_answer_timestamp",
        type_="datetime64[ns]"
    )
)

In [ ]:
context.suites.add(order_review_suite)

In [ ]:
order_review_results=order_review_batch.validate(order_review_suite)

order_review_results

### Review ID Uniqueness

A uniqueness check was initially applied to the `review_id` column.  
Validation showed that some review IDs appear more than once, indicating that the raw dataset allows duplicate review records.

The uniqueness constraint was therefore removed, and `review_id` is validated for non-null values only.  
This behaviour is treated as a characteristic of the source data rather than a data quality error.

Uniqueness may be enforced after data cleaning or deduplication in future work.


In [ ]:
df_order_payments.info()

In [ ]:
df_order_payments['payment_installments'].min()

In [ ]:
order_payments_asset=data_source.add_dataframe_asset(
    name='order_payments'
)

order_payments_batch_def=order_payments_asset.add_batch_definition_whole_dataframe('order_payments_batch')

order_payments_batch=order_payments_batch_def.get_batch(batch_parameters={'dataframe':df_order_payments})

order_payments_suite=gx.ExpectationSuite(name='order_payments_suite')


In [ ]:
order_payments_suite.add_expectation(
    gx.expectations.ExpectColumnValuesToNotBeNull(
        column="order_id"
    )
)

order_payments_suite.add_expectation(
    gx.expectations.ExpectColumnValuesToNotBeNull(
        column="payment_sequential"
    )
)

order_payments_suite.add_expectation(
    gx.expectations.ExpectColumnValuesToBeBetween(
        column="payment_sequential",
        min_value=1
    )
)

order_payments_suite.add_expectation(
    gx.expectations.ExpectColumnValuesToBeInSet(
        column="payment_type",
        value_set=[
            "credit_card",
            "boleto",
            "voucher",
            "debit_card",
            "not_defined"
        ]
    )
)

order_payments_suite.add_expectation(
    gx.expectations.ExpectColumnValuesToNotBeNull(
        column="payment_installments"
    )
)

order_payments_suite.add_expectation(
    gx.expectations.ExpectColumnValuesToBeBetween(
        column="payment_installments",
        min_value=0
    )
)

order_payments_suite.add_expectation(
    gx.expectations.ExpectColumnValuesToNotBeNull(
        column="payment_value"
    )
)

order_payments_suite.add_expectation(
    gx.expectations.ExpectColumnValuesToBeBetween(
        column="payment_value",
        min_value=0
    )
)

In [ ]:
context.suites.add(order_payments_suite)

In [ ]:
order_payments_results=order_payments_batch.validate(order_payments_suite)

order_payments_results

In [ ]:
df_products.info()

In [ ]:
df_products['product_width_cm'].min()

In [ ]:
products_asset=data_source.add_dataframe_asset(
    name='products'
)

products_batch_def=products_asset.add_batch_definition_whole_dataframe('products_batch')

products_batch=products_batch_def.get_batch(batch_parameters={'dataframe':df_products})

products_suite=gx.ExpectationSuite(name='products_suite')


In [ ]:
products_suite.add_expectation(
    gx.expectations.ExpectColumnValuesToNotBeNull(
        column='product_id'
    )
)

products_suite.add_expectation(
    gx.expectations.ExpectColumnValuesToBeUnique(
        column='product_id'
    )
)

for col in [
    'product_weight_g',
    'product_length_cm',
    'product_height_cm',
    'product_width_cm'
]:
    products_suite.add_expectation(
        gx.expectations.ExpectColumnValuesToBeBetween(
            column=col,
            min_value=0,
            mostly=0.99
        )
    )

products_suite.add_expectation(
    gx.expectations.ExpectColumnValuesToBeBetween(
        column='product_photos_qty',
        min_value=0,
        mostly=0.98
    )
)

In [ ]:
context.suites.add(products_suite)

In [ ]:
products_results=products_batch.validate(products_suite)

products_results

In [ ]:
df_sellers.info()

In [ ]:
df_sellers.isna().sum()

In [ ]:
sellers_asset=data_source.add_dataframe_asset(
    name='sellers'
)

sellers_batch_def=sellers_asset.add_batch_definition_whole_dataframe('sellers_batch')

sellers_batch=sellers_batch_def.get_batch(batch_parameters={'dataframe':df_sellers})

sellers_suite=gx.ExpectationSuite(name='sellers_suite')

In [ ]:
sellers_suite.add_expectation(
    gx.expectations.ExpectColumnValuesToNotBeNull(
        column="seller_id"
    )
)

sellers_suite.add_expectation(
    gx.expectations.ExpectColumnValuesToBeUnique(
        column="seller_id"
    )
)

sellers_suite.add_expectation(
    gx.expectations.ExpectColumnValuesToNotBeNull(
        column="seller_zip_code_prefix"
    )
)

sellers_suite.add_expectation(
    gx.expectations.ExpectColumnValuesToBeBetween(
        column="seller_zip_code_prefix",
        min_value=1
    )
)

sellers_suite.add_expectation(
    gx.expectations.ExpectColumnValuesToNotBeNull(
        column="seller_state"
    )
)

sellers_suite.add_expectation(
    gx.expectations.ExpectColumnValueLengthsToBeBetween(
        column="seller_state",
        min_value=2,
        max_value=2
    )
)

In [ ]:
context.suites.add(sellers_suite)

In [ ]:
sellers_results=sellers_batch.validate(sellers_suite)

sellers_results

In [ ]:
df_product_category.info()

In [ ]:
df_product_category.isna().sum()

In [ ]:
df_product_category['product_category_name'].min()

In [ ]:
df_product_category['product_category_name_english'].min()

In [ ]:
product_category_asset=data_source.add_dataframe_asset(
    name='product_category'
)

product_category_batch_def=product_category_asset.add_batch_definition_whole_dataframe('product_category_batch')

product_category_batch=product_category_batch_def.get_batch(batch_parameters={'dataframe':df_product_category})

product_category_suite=gx.ExpectationSuite(name='product_category_suite')

In [ ]:
product_category_suite.add_expectation(
    gx.expectations.ExpectColumnValuesToNotBeNull(
        column="product_category_name"
    )
)

product_category_suite.add_expectation(
    gx.expectations.ExpectColumnValuesToBeUnique(
        column="product_category_name"
    )
)

product_category_suite.add_expectation(
    gx.expectations.ExpectColumnValuesToNotBeNull(
        column="product_category_name_english"
    )
)

product_category_suite.add_expectation(
    gx.expectations.ExpectColumnValuesToBeUnique(
        column="product_category_name_english"
    )
)

product_category_suite.add_expectation(
    gx.expectations.ExpectColumnValueLengthsToBeBetween(
        column="product_category_name",
        min_value=1
    )
)

product_category_suite.add_expectation(
    gx.expectations.ExpectColumnValueLengthsToBeBetween(
        column="product_category_name_english",
        min_value=1
    )
)


In [ ]:
context.suites.add(product_category_suite)

In [ ]:
product_category_results=product_category_batch.validate(product_category_suite)

product_category_results

In [ ]:
#pip install sqlalchemy pyodbc pandas


# 2


In [378]:
!pip install psycopg2-binary sqlalchemy

/opt/anaconda3/lib/python3.13/pty.py:95: DeprecationWarning: This process (pid=7378) is multi-threaded, use of forkpty() may lead to deadlocks in the child.
  pid, fd = os.forkpty()


   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.9/3.9 MB 2.0 MB/s  0:00:01m 2.0 MB/s eta 0:00:01

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: pip install --upgrade pip


In [385]:
from sqlalchemy import create_engine

engine = create_engine(
    "postgresql+psycopg2://postgres:postgres@localhost:5432/olist_dw"
)

In [386]:
engine.connect()

In [380]:
def build_dim_date(df_orders, df_order_item):
  date_cols_orders=[
      'order_purchase_timestamp',
      'order_approved_at',
      'order_delivered_carrier_date',
      'order_delivered_customer_date',
      'order_estimated_delivery_date',
  ]

  date_cols_items=['shipping_limit_date']

  dates=[]

  for c in date_cols_orders:
    if c in df_orders.columns:
      dates.append(df_orders[c].dt.date)

  for c in date_cols_items:
    if c in df_order_item.columns:
      dates.append(df_order_item[c].dt.date)

  all_dates=pd.concat(dates).dropna().unique()
  df=pd.DataFrame({'full_date':pd.to_datetime(all_dates)})
  df = df.drop_duplicates(subset=['full_date'])
    
  df['date_sk']=df['full_date'].dt.strftime('%Y%m%d').astype(int)
  df['day']=df['full_date'].dt.day
  df['month']=df['full_date'].dt.month
  df['month_name']=df['full_date'].dt.strftime('%B')
  df['quarter']=df['full_date'].dt.quarter
  df['year']=df['full_date'].dt.year
  df['day_of_week']=df['full_date'].dt.weekday+1
  df['is_weekend']=df['day_of_week'].isin([6, 7])

  return df.sort_values('full_date')

In [381]:
dim_date_df=build_dim_date(df_orders, df_order_item)
dim_date_df.head()

,full_date,date_sk,day,month,month_name,quarter,year,day_of_week,is_weekend
594,2016-09-04,20160904,4,9,September,3,2016,7,True
593,2016-09-05,20160905,5,9,September,3,2016,1,False
610,2016-09-13,20160913,13,9,September,3,2016,2,False
618,2016-09-15,20160915,15,9,September,3,2016,4,False
717,2016-09-19,20160919,19,9,September,3,2016,1,False


In [383]:
dim_date_df.shape

(720, 9)

In [387]:
dim_date_df.to_sql(
    'dim_date',
    engine,
    schema='dim',
    if_exists='append',
    index=False
)

720

with engine.begin() as conn:
    conn.rollback()


engine = create_engine(
    f"mssql+pyodbc:///?odbc_connect={params}",
    fast_executemany=True
)


In [388]:
pd.read_sql(
    "SELECT COUNT(*) AS row_count FROM dim.dim_date",
    engine
)


,row_count
0,720


In [389]:
def build_dim_geography(df_geolocation):

  def mode_or_null(series):
    s=series.dropna()
    if s.empty:
      return None
    return s.value_counts().idxmax()

  dim_geo_df=(
      df_geolocation
      .groupby('geolocation_zip_code_prefix', as_index=False)
      .agg(
          city=('geolocation_city', mode_or_null),
          state=('geolocation_state', mode_or_null),
          lat=('geolocation_lat', 'mean'),
          lng=('geolocation_lng', 'mean')
      )
      .rename(columns={'geolocation_zip_code_prefix':'zip_code_prefix'})
  )
  return dim_geo_df

In [390]:
dim_geo_df=build_dim_geography(df_geolocation)
dim_geo_df.head()

,zip_code_prefix,city,state,lat,lng
0,1001,sao paulo,SP,-23.550190,-46.634024
1,1002,sao paulo,SP,-23.548146,-46.634979
2,1003,sao paulo,SP,-23.548994,-46.635731
3,1004,sao paulo,SP,-23.549799,-46.634757
4,1005,sao paulo,SP,-23.549456,-46.636733


In [393]:
dim_geo_df.shape

(19015, 5)

In [392]:
dim_geo_df.to_sql(
    "dim_geography",
    engine,
    schema="dim",
    if_exists="append",
    index=False
)


15

In [394]:
pd.read_sql(
    'SELECT COUNT(*) AS row_count FROM dim.dim_geography',
    engine
)

,row_count
0,19015


In [395]:
def build_dim_customer(customers_df, dim_geo_df):

    dim_customer_df=(
        customers_df.loc[:, [
            'customer_unique_id',
            'customer_zip_code_prefix',
            'customer_city',
            'customer_state'
        ]]
        .drop_duplicates(subset=['customer_unique_id'])
        .merge(
            dim_geo_df[['geo_sk','zip_code_prefix']],
            left_on='customer_zip_code_prefix',
            right_on='zip_code_prefix',
            how='left'
        )
        .rename(columns={'geo_sk':'customer_geo_sk'})
        .drop(columns=['zip_code_prefix'])
        .reset_index(drop=True)
    )
    return dim_customer_df

In [397]:
dim_geo_df=pd.read_sql(
    'SELECT geo_sk, zip_code_prefix FROM dim.dim_geography;',
    engine
)

In [398]:
dim_customer_df=build_dim_customer(df_customers, dim_geo_df)
dim_customer_df.head()

,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state,customer_geo_sk
0,861eff4711a542e4b93843c6dd7febb0,14409,franca,SP,5359.0
1,290c77bc529b7ac935b93aa66c333dc3,9790,sao bernardo do campo,SP,4280.0
2,060e732b5b29e8181a18229c7b0b2b5e,1151,sao paulo,SP,85.0
3,259dac757896d24d7702b9acbbff3f3c,8775,mogi das cruzes,SP,4029.0
4,345ecd01c38d18a9036ed96c73b8d066,13056,campinas,SP,4836.0


In [399]:
dim_customer_df.shape

(96096, 5)

In [402]:
dim_customer_df.to_sql(
    name='dim_customer',
    con=engine,
    schema='dim',
    if_exists='append',
    index=False
)

96

In [403]:
pd.read_sql(
    'SELECT COUNT(*) AS row_count FROM dim.dim_customer',
    engine
)

,row_count
0,96096


In [404]:
def build_dim_seller(df_sellers, geo_dim_df):
    dim_seller_df=(
        df_sellers.loc[:,[
            'seller_id',
            'seller_zip_code_prefix',
            'seller_city',
            'seller_state'
        ]]
        .drop_duplicates(subset=['seller_id'])
        .merge(
           geo_dim_df[['geo_sk','zip_code_prefix']], 
            left_on='seller_zip_code_prefix',
            right_on='zip_code_prefix',
            how='left'
        )
        .rename(columns={'geo_sk':'seller_geo_sk'})
        .drop(columns=['zip_code_prefix'])
        .reset_index(drop=True)
    )
    return dim_seller_df

In [405]:
dim_geo_df=pd.read_sql(
    'SELECT geo_sk, zip_code_prefix FROM dim.dim_geography',
    engine
)

In [406]:
dim_seller_df=build_dim_seller(df_sellers, dim_geo_df)
dim_seller_df.head()

,seller_id,seller_zip_code_prefix,seller_city,seller_state,seller_geo_sk
0,3442f8959a84dea7ee197c632cb2df15,13023,campinas,SP,4811.0
1,d1b65fc7debc3361ea86b5f14c68d2e2,13844,mogi guacu,SP,5210.0
2,ce3ad9de960102d0677a81f5d0bb7b2d,20031,rio de janeiro,RJ,6355.0
3,c0f3eea2e14555b6faeea3dd58c1b1c3,4195,sao paulo,SP,1834.0
4,51a04a8a6bdcb23deccc82b0b80742cf,12914,braganca paulista,SP,4773.0


In [407]:
dim_seller_df.shape

(3095, 5)

In [408]:
dim_seller_df.to_sql(
    name='dim_seller',
    con=engine,
    schema='dim',
    if_exists='append',
    index=False
)

95

In [409]:
pd.read_sql(
    'SELECT COUNT(*) AS row_count FROM dim.dim_seller',
    engine
)

,row_count
0,3095


In [413]:
def build_dim_product(df_products):
    dim_product_df=(
        df_products.loc[:,[
            'product_id',
            'product_category_name',             
            'product_category_name_english',
            'product_weight_g',
            'product_length_cm',
            'product_height_cm',
            'product_width_cm',
            'product_photos_qty',
            'product_name_lenght',
            'product_description_lenght'
        ]]
        .drop_duplicates(subset=['product_id'])
        .reset_index(drop=True)
    )
    return dim_product_df

In [414]:
dim_product_df=build_dim_product(df_products)
dim_product_df.head()

,product_id,product_category_name,product_category_name_english,product_weight_g,product_length_cm,product_height_cm,product_width_cm,product_photos_qty,product_name_lenght,product_description_lenght
0,1e9e8ef04dbcff4541ed26657ea517e5,perfumaria,perfumery,225.0,16.0,10.0,14.0,1.0,40.0,287.0
1,3aa071139cb16b67ca9e5dea641aaa2f,artes,art,1000.0,30.0,18.0,20.0,1.0,44.0,276.0
2,96bd76ec8810374ed1b65e291975717f,esporte_lazer,sports_leisure,154.0,18.0,9.0,15.0,1.0,46.0,250.0
3,cef67bcfe19066a932b7673e239eb23d,bebes,baby,371.0,26.0,4.0,26.0,1.0,27.0,261.0
4,9dc1a7de274444849c219cff195d0b71,utilidades_domesticas,housewares,625.0,20.0,17.0,13.0,4.0,37.0,402.0


In [415]:
dim_product_df.shape

(32951, 10)

In [417]:
dim_product_df=dim_product_df.rename(columns={
    'product_name_lenght':'product_name_length',
    'product_description_lenght':'product_description_length'
})

In [418]:
dim_product_df.to_sql(
    name='dim_product',
    con=engine,
    schema='dim',
    if_exists='append',
    index=False
)

951

In [419]:
pd.read_sql(
    'SELECT COUNT(*) AS row_count FROM dim.dim_product',
    engine
)

,row_count
0,32951


In [421]:
df_orders.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 11 columns):
 #   Column                         Non-Null Count  Dtype         
---  ------                         --------------  -----         
 0   order_id                       99441 non-null  object        
 1   customer_id                    99441 non-null  object        
 2   order_status                   99441 non-null  category      
 3   order_purchase_timestamp       99441 non-null  datetime64[ns]
 4   order_approved_at              99281 non-null  datetime64[ns]
 5   order_delivered_carrier_date   97658 non-null  datetime64[ns]
 6   order_delivered_customer_date  96476 non-null  datetime64[ns]
 7   order_estimated_delivery_date  99441 non-null  datetime64[ns]
 8   delivery_duration_days         96476 non-null  float64       
 9   is_late_delivery               99441 non-null  bool          
 10  is_failed_order                99441 non-null  bool          
dtypes: bool(2), cat

In [443]:
def build_fact_orders(df_orders, df_customers, engine):

    # Load dimension tables
    customer_dim = pd.read_sql(
        "SELECT customer_sk, customer_unique_id FROM dim.dim_customer",
        engine
    )

    date_dim = pd.read_sql(
        "SELECT date_sk, full_date FROM dim.dim_date",
        engine
    )

    date_dim["full_date"] = pd.to_datetime(date_dim["full_date"]).dt.date

    customer_lookup = df_customers[
        ["customer_id", "customer_unique_id"]
    ]

    fact_df = df_orders.merge(
        customer_lookup,
        on="customer_id",
        how="left"
    )

    fact_df = fact_df.merge(
        customer_dim,
        on="customer_unique_id",
        how="left"
    )

    date_cols = [
        "order_purchase_timestamp",
        "order_approved_at",
        "order_delivered_carrier_date",
        "order_delivered_customer_date",
        "order_estimated_delivery_date"
    ]

    for col in date_cols:
        fact_df[col] = pd.to_datetime(fact_df[col]).dt.date

    def resolve_date_sk(df, date_col, sk_name):
        df = df.merge(
            date_dim,
            left_on=date_col,
            right_on="full_date",
            how="left"
        )

        df = df.rename(
            columns={"date_sk": sk_name}
        ).drop(columns=["full_date"])

        return df

    fact_df = resolve_date_sk(
        fact_df,
        "order_purchase_timestamp",
        "purchase_date_sk"
    )

    fact_df = resolve_date_sk(
        fact_df,
        "order_approved_at",
        "approved_date_sk"
    )

    fact_df = resolve_date_sk(
        fact_df,
        "order_delivered_carrier_date",
        "carrier_handoff_date_sk"
    )

    fact_df = resolve_date_sk(
        fact_df,
        "order_delivered_customer_date",
        "delivered_customer_date_sk"
    )

    fact_df = resolve_date_sk(
        fact_df,
        "order_estimated_delivery_date",
        "estimated_delivery_date_sk"
    )

    fact_df["delivery_duration_days"] = (
        pd.to_datetime(fact_df["order_delivered_customer_date"]) -
        pd.to_datetime(fact_df["order_purchase_timestamp"])
    ).dt.days

    delay = (
        pd.to_datetime(fact_df["order_delivered_customer_date"]) -
        pd.to_datetime(fact_df["order_estimated_delivery_date"])
    ).dt.days

    fact_df["delivery_delay_days"] = delay.apply(
        lambda x: x if pd.notnull(x) and x > 0 else 0
    )

    fact_df["is_delivered_flag"] = fact_df["order_status"].eq("delivered")

    fact_df["is_late_delivery"] = fact_df["delivery_delay_days"] > 0

    fact_df["is_failed_order"] = ~fact_df["order_status"].eq("delivered")

    fact_df["issue_flag"] = (
        fact_df["is_late_delivery"] |
        fact_df["is_failed_order"]
    )

    final_cols = [
        "order_id",
        "customer_id",
        "customer_sk",
        "purchase_date_sk",
        "approved_date_sk",
        "carrier_handoff_date_sk",
        "delivered_customer_date_sk",
        "estimated_delivery_date_sk",
        "order_status",
        "delivery_duration_days",
        "delivery_delay_days",
        "is_delivered_flag",
        "is_late_delivery",
        "is_failed_order",
        "issue_flag"
    ]

    return fact_df[final_cols]

In [444]:
fact_orders_df.shape

(99441, 15)

In [445]:
fact_orders_df.to_sql(
    name='fact_orders',
    con=engine,
    schema='fact',
    if_exists='append',
    index=False
)

441

In [446]:
pd.read_sql(
    'SELECT COUNT(*) FROM fact.fact_orders',
    engine
)

,count
0,99441


In [448]:
def build_fact_order_items(df_order_items, engine):

    product_dim = pd.read_sql(
        "SELECT product_id, product_sk FROM dim.dim_product",
        engine
    )

    seller_dim = pd.read_sql(
        "SELECT seller_id, seller_sk FROM dim.dim_seller",
        engine
    )

    date_dim = pd.read_sql(
        "SELECT date_sk, full_date FROM dim.dim_date",
        engine
    )

    fact_orders_lookup = pd.read_sql(
        """
        SELECT order_id, customer_sk, purchase_date_sk
        FROM fact.fact_orders
        """,
        engine
    )

    date_dim["full_date"] = pd.to_datetime(date_dim["full_date"]).dt.date

    # Start with order_items
    fact_df = df_order_items.copy()

    # Product SK
    fact_df = fact_df.merge(
        product_dim,
        on="product_id",
        how="left"
    )

    # Seller SK
    fact_df = fact_df.merge(
        seller_dim,
        on="seller_id",
        how="left"
    )

    # Customer SK + purchase_date_sk
    fact_df = fact_df.merge(
        fact_orders_lookup,
        on="order_id",
        how="left"
    )

    # Shipping limit date → date_sk
    fact_df["shipping_limit_date"] = pd.to_datetime(
        fact_df["shipping_limit_date"]
    ).dt.date

    fact_df = fact_df.merge(
        date_dim,
        left_on="shipping_limit_date",
        right_on="full_date",
        how="left"
    ).rename(columns={"date_sk": "shipping_limit_date_sk"}).drop(columns=["full_date"])

    # Measure
    fact_df["item_total_value"] = (
        fact_df["price"] + fact_df["freight_value"]
    )

    final_cols = [
        "order_id",
        "order_item_id",
        "product_sk",
        "seller_sk",
        "customer_sk",
        "purchase_date_sk",
        "shipping_limit_date_sk",
        "price",
        "freight_value",
        "item_total_value"
    ]

    return fact_df[final_cols]

In [453]:
fact_order_items_df=build_fact_order_items(df_order_item_enriched, engine)

In [454]:
fact_order_items_df.shape

(112650, 10)

In [456]:
fact_order_items_df.to_sql(
    name='fact_order_items',
    con=engine,
    schema='fact',
    if_exists='append',
    index=False
)

650

In [457]:
pd.read_sql(
    'SELECT COUNT(*) FROM fact.fact_order_items',
    engine
)

,count
0,112650


In [480]:
def build_fact_seller_order(df_order_items, engine):
    seller_dim=pd.read_sql(
        'SELECT seller_sk, seller_id FROM dim.dim_seller',
        engine
    )
    fact_orders=pd.read_sql(
        '''
        SELECT
            order_id,
            customer_sk,
            purchase_date_sk,
            is_delivered_flag,
            is_late_delivery,
            is_failed_order,
            delivery_delay_days
        FROM fact.fact_orders
        ''',
        engine
    )

    agg=(
        df_order_items
        .groupby(['order_id', 'seller_id'], as_index=False)
        .agg(
            seller_order_revenue=('price', 'sum'),
            seller_order_freight=('freight_value', 'sum'),
            seller_order_items_count=('order_item_id', 'count')
        )
    )
    agg=agg.merge(seller_dim, on='seller_id', how='left')

    fact_df=agg.merge(fact_orders, on='order_id', how='left')

    fact_df["is_late_delivery"] = fact_df["is_late_delivery"].fillna(False)
    fact_df["is_failed_order"] = fact_df["is_failed_order"].fillna(False)
    fact_df["is_delivered_flag"] = fact_df["is_delivered_flag"].fillna(False)
    fact_df["delivery_delay_days"] = fact_df["delivery_delay_days"].fillna(0)

    final_cols=[
        'order_id',
        'seller_sk',
        'customer_sk',
        'purchase_date_sk',
        'seller_order_revenue',
        'seller_order_freight',
        'seller_order_items_count',
        'is_late_delivery',
        'is_delivered_flag',
        'is_failed_order',
        'delivery_delay_days'
    ]
    return fact_df[final_cols]

In [481]:
fact_seller_order_df=build_fact_seller_order(df_order_item_enriched, engine)

In [482]:
fact_seller_order_df.shape

(100010, 11)

In [483]:
fact_seller_order_df.to_sql(
    name='fact_seller_order',
    con=engine,
    schema='fact',
    if_exists='append',
    index=False
)

10

In [489]:
pd.read_sql(
    '''
    SELECT COUNT(DISTINCT seller_id) AS total_sellers
    FROM dim.dim_seller
    ''',
    engine
)

,total_sellers
0,3095


In [486]:
df_customers.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 8 columns):
 #   Column                       Non-Null Count  Dtype  
---  ------                       --------------  -----  
 0   customer_id                  99441 non-null  object 
 1   customer_unique_id           99441 non-null  object 
 2   customer_zip_code_prefix     99441 non-null  int64  
 3   customer_city                99441 non-null  object 
 4   customer_state               99441 non-null  object 
 5   geolocation_zip_code_prefix  99163 non-null  float64
 6   lat                          99163 non-null  float64
 7   lng                          99163 non-null  float64
dtypes: float64(3), int64(1), object(4)
memory usage: 6.1+ MB
